"""The declarations of the design document: all 22 processes, the fields, groups, tables and stages.

Generated once from the script that checked the design (build step 0). The scheduler tests use it to show
that the engine computes the order the design document shows, and makes every refusal it promises.
"""
STAGES = ['setup', 'geological', 'climate', 'weather']
CLOCKS = {'setup': 'once', 'geological': 'geological', 'climate': 'climate', 'weather': 'weather'}
GROUPS = ['crust_thickness_tendency', 'moisture_source', 'surface_heat_flux']
TABLES = ['table:crust_points', 'table:lakes', 'table:plates', 'table:seas', 'table:storms', 'table:surface_age_points', 'table:tectonic_events']
LABELS = {'place_label': 'climate'}
GEOMETRY = ['cell_area', 'coriolis_parameter', 'latitude', 'longitude']
KINDS = {'albedo': 'number',
 'baroclinicity': 'number',
 'basin_id': 'index',
 'biome': 'category',
 'boundary_distance': 'number',
 'boundary_kind': 'category',
 'cell_area': 'number',
 'climate_class': 'category',
 'coast_distance': 'number',
 'column_water': 'number',
 'convergence_rate': 'number',
 'coriolis_parameter': 'number',
 'crust_thickness': 'number',
 'crust_type': 'category',
 'daily_temperature_spread': 'number',
 'depression_id': 'index',
 'drainage_area': 'number',
 'elevation': 'number',
 'erodibility': 'number',
 'erosion_rate': 'number',
 'erosion_thinning': 'number',
 'evapotranspiration': 'number',
 'flow_receiver': 'index',
 'height_above_sea': 'number',
 'insolation': 'number',
 'lake_fraction': 'number',
 'lake_level': 'number',
 'latitude': 'number',
 'longitude': 'number',
 'ocean_crust_age': 'number',
 'ocean_current': 'direction',
 'ocean_evaporation': 'number',
 'ocean_heat_convergence': 'number',
 'ocean_mask': 'boolean',
 'orogeny_age': 'number',
 'permafrost': 'number',
 'place_label': 'category',
 'plate_id': 'index',
 'plate_velocity': 'direction',
 'potential_evapotranspiration': 'number',
 'potential_intensity': 'number',
 'precipitation': 'number',
 'river_discharge': 'number',
 'rock_type': 'category',
 'runoff': 'number',
 'runoff_annual': 'number',
 'sea_depth': 'number',
 'sea_level_pressure': 'number',
 'slope': 'number',
 'snow_ice_cover': 'number',
 'snow_water': 'number',
 'snowfall': 'number',
 'soil_depth': 'number',
 'soil_fertility': 'number',
 'soil_moisture': 'number',
 'soil_order': 'category',
 'soil_water_capacity': 'number',
 'spill_elevation': 'number',
 'steering_wind': 'direction',
 'storm_influence': 'number',
 'storm_track_density': 'number',
 'subsidence': 'number',
 'surface_age': 'number',
 'surface_temperature': 'number',
 'tc_genesis_potential': 'number',
 'upwelling': 'number',
 'vegetation_cover': 'number',
 'volcanism': 'number',
 'weather_precipitation': 'number',
 'weather_pressure': 'number',
 'weather_temperature': 'number',
 'weather_wind': 'direction',
 'wet_day_fraction': 'number',
 'wind': 'direction'}
P = {'PlanetGeometry': {'stage': 'setup',
                    'reads': [],
                    'lagged': [],
                    'writes': ['latitude', 'longitude', 'cell_area', 'coriolis_parameter'],
                    'modifies': [],
                    'contributes': {},
                    'lagged_group': [],
                    'group_reads': [],
                    'order': None,
                    'start': False},
 'Tectonics': {'stage': 'geological',
               'reads': ['cell_area'],
               'lagged': ['table:crust_points', 'table:plates', 'table:tectonic_events'],
               'writes': ['plate_id', 'plate_velocity', 'crust_type', 'crust_thickness', 'ocean_crust_age', 'orogeny_age', 'boundary_kind',
                          'boundary_distance', 'convergence_rate', 'volcanism', 'table:crust_points', 'table:plates', 'table:tectonic_events'],
               'modifies': [],
               'contributes': {},
               'lagged_group': ['crust_thickness_tendency'],
               'group_reads': [],
               'order': None,
               'start': True},
 'Lithology': {'stage': 'geological',
               'reads': ['crust_type', 'orogeny_age', 'volcanism', 'boundary_kind'],
               'lagged': [],
               'writes': ['rock_type', 'erodibility'],
               'modifies': [],
               'contributes': {},
               'lagged_group': [],
               'group_reads': [],
               'order': None,
               'start': False},
 'Isostasy': {'stage': 'geological',
              'reads': ['crust_type', 'crust_thickness', 'ocean_crust_age'],
              'lagged': [],
              'writes': ['elevation'],
              'modifies': [],
              'contributes': {},
              'lagged_group': [],
              'group_reads': [],
              'order': None,
              'start': False},
 'FluvialErosion': {'stage': 'geological',
                    'reads': ['erodibility', 'cell_area'],
                    'lagged': ['runoff_annual', 'table:seas'],
                    'writes': ['erosion_rate'],
                    'modifies': ['elevation'],
                    'contributes': {'crust_thickness_tendency': 'erosion_thinning'},
                    'lagged_group': [],
                    'group_reads': [],
                    'order': 10,
                    'start': False},
 'SeaLevel': {'stage': 'geological',
              'reads': ['elevation', 'cell_area'],
              'lagged': [],
              'writes': ['ocean_mask', 'sea_depth', 'height_above_sea', 'coast_distance', 'table:seas'],
              'modifies': [],
              'contributes': {},
              'lagged_group': [],
              'group_reads': [],
              'order': None,
              'start': False},
 'Drainage': {'stage': 'geological',
              'reads': ['elevation', 'ocean_mask', 'cell_area'],
              'lagged': [],
              'writes': ['flow_receiver', 'drainage_area', 'basin_id', 'depression_id', 'spill_elevation', 'slope'],
              'modifies': [],
              'contributes': {},
              'lagged_group': [],
              'group_reads': [],
              'order': None,
              'start': False},
 'SurfaceAge': {'stage': 'geological',
                'reads': ['erosion_rate', 'volcanism', 'ocean_mask', 'table:crust_points'],
                'lagged': ['table:surface_age_points'],
                'writes': ['surface_age', 'table:surface_age_points'],
                'modifies': [],
                'contributes': {},
                'lagged_group': [],
                'group_reads': [],
                'order': None,
                'start': True},
 'Insolation': {'stage': 'climate',
                'reads': ['latitude'],
                'lagged': [],
                'writes': ['insolation'],
                'modifies': [],
                'contributes': {},
                'lagged_group': [],
                'group_reads': [],
                'order': None,
                'start': False},
 'Albedo': {'stage': 'climate',
            'reads': ['ocean_mask', 'latitude'],
            'lagged': ['snow_ice_cover', 'vegetation_cover'],
            'writes': ['albedo'],
            'modifies': [],
            'contributes': {},
            'lagged_group': [],
            'group_reads': [],
            'order': None,
            'start': False},
 'EnergyBalance': {'stage': 'climate',
                   'reads': ['insolation', 'albedo', 'ocean_mask', 'height_above_sea', 'cell_area'],
                   'lagged': ['wind'],
                   'writes': ['surface_temperature'],
                   'modifies': [],
                   'contributes': {},
                   'lagged_group': ['surface_heat_flux'],
                   'group_reads': [],
                   'order': None,
                   'start': False},
 'Cryosphere': {'stage': 'climate',
                'reads': ['surface_temperature', 'ocean_mask'],
                'lagged': ['snow_water'],
                'writes': ['snow_ice_cover', 'permafrost'],
                'modifies': [],
                'contributes': {},
                'lagged_group': [],
                'group_reads': [],
                'order': None,
                'start': False},
 'Circulation': {'stage': 'climate',
                 'reads': ['surface_temperature', 'coriolis_parameter', 'latitude', 'height_above_sea', 'ocean_mask', 'cell_area'],
                 'lagged': [],
                 'writes': ['sea_level_pressure', 'wind', 'steering_wind', 'subsidence', 'baroclinicity'],
                 'modifies': [],
                 'contributes': {},
                 'lagged_group': [],
                 'group_reads': [],
                 'order': None,
                 'start': False},
 'OceanCurrents': {'stage': 'climate',
                   'reads': ['wind', 'ocean_mask', 'coriolis_parameter', 'surface_temperature', 'cell_area'],
                   'lagged': [],
                   'writes': ['ocean_current', 'upwelling'],
                   'modifies': [],
                   'contributes': {'surface_heat_flux': 'ocean_heat_convergence'},
                   'lagged_group': [],
                   'group_reads': [],
                   'order': None,
                   'start': False},
 'Moisture': {'stage': 'climate',
              'reads': ['wind', 'subsidence', 'surface_temperature', 'height_above_sea', 'ocean_mask', 'baroclinicity', 'cell_area'],
              'lagged': [],
              'writes': ['ocean_evaporation', 'column_water', 'precipitation', 'snowfall'],
              'modifies': [],
              'contributes': {},
              'lagged_group': ['moisture_source'],
              'group_reads': [],
              'order': None,
              'start': False},
 'Hydrology': {'stage': 'climate',
               'reads': ['precipitation', 'snowfall', 'surface_temperature', 'insolation', 'albedo', 'elevation', 'flow_receiver', 'depression_id',
                         'spill_elevation', 'cell_area', 'ocean_mask'],
               'lagged': ['soil_water_capacity', 'vegetation_cover'],
               'writes': ['potential_evapotranspiration', 'soil_moisture', 'snow_water', 'runoff', 'runoff_annual', 'river_discharge',
                          'lake_fraction', 'lake_level', 'table:lakes'],
               'modifies': [],
               'contributes': {'moisture_source': 'evapotranspiration'},
               'lagged_group': [],
               'group_reads': [],
               'order': None,
               'start': False},
 'Soils': {'stage': 'climate',
           'reads': ['surface_temperature', 'precipitation', 'potential_evapotranspiration', 'soil_moisture', 'rock_type', 'slope', 'surface_age',
                     'erosion_rate', 'permafrost', 'snow_ice_cover'],
           'lagged': ['vegetation_cover', 'biome'],
           'writes': ['soil_order', 'soil_depth', 'soil_water_capacity', 'soil_fertility'],
           'modifies': [],
           'contributes': {},
           'lagged_group': [],
           'group_reads': [],
           'order': None,
           'start': False},
 'Biomes': {'stage': 'climate',
            'reads': ['surface_temperature', 'precipitation', 'potential_evapotranspiration', 'soil_moisture', 'soil_water_capacity',
                      'soil_fertility', 'permafrost', 'snow_ice_cover', 'ocean_mask'],
            'lagged': [],
            'writes': ['climate_class', 'biome', 'vegetation_cover'],
            'modifies': [],
            'contributes': {},
            'lagged_group': [],
            'group_reads': [],
            'order': None,
            'start': False},
 'StormClimatology': {'stage': 'climate',
                      'reads': ['surface_temperature', 'wind', 'steering_wind', 'baroclinicity', 'column_water', 'ocean_mask', 'coriolis_parameter'],
                      'lagged': [],
                      'writes': ['tc_genesis_potential', 'potential_intensity', 'storm_track_density'],
                      'modifies': [],
                      'contributes': {},
                      'lagged_group': [],
                      'group_reads': [],
                      'order': None,
                      'start': False},
 'WeatherStatistics': {'stage': 'climate',
                       'reads': ['surface_temperature', 'height_above_sea', 'storm_track_density', 'precipitation', 'ocean_mask'],
                       'lagged': [],
                       'writes': ['daily_temperature_spread', 'wet_day_fraction'],
                       'modifies': [],
                       'contributes': {},
                       'lagged_group': [],
                       'group_reads': [],
                       'order': None,
                       'start': False},
 'SynopticStorms': {'stage': 'weather',
                    'reads': ['storm_track_density', 'tc_genesis_potential', 'potential_intensity', 'steering_wind', 'ocean_mask',
                              'surface_temperature', 'coriolis_parameter', 'cell_area'],
                    'lagged': [],
                    'writes': ['storm_influence', 'table:storms'],
                    'modifies': [],
                    'contributes': {},
                    'lagged_group': [],
                    'group_reads': [],
                    'order': None,
                    'start': False},
 'DailyWeather': {'stage': 'weather',
                  'reads': ['surface_temperature', 'precipitation', 'snowfall', 'wind', 'sea_level_pressure', 'daily_temperature_spread',
                            'wet_day_fraction', 'storm_influence', 'coriolis_parameter', 'height_above_sea', 'cell_area'],
                  'lagged': [],
                  'writes': ['weather_temperature', 'weather_precipitation', 'weather_wind', 'weather_pressure'],
                  'modifies': [],
                  'contributes': {},
                  'lagged_group': [],
                  'group_reads': [],
                  'order': None,
                  'start': False}}
DESIGN_ORDER = {'setup': ['PlanetGeometry'],
 'geological': ['Tectonics', 'Isostasy', 'Lithology', 'FluvialErosion', 'SeaLevel', 'Drainage', 'SurfaceAge'],
 'climate': ['Albedo', 'Insolation', 'EnergyBalance', 'Circulation', 'Cryosphere', 'Moisture', 'Hydrology', 'OceanCurrents', 'Soils', 'Biomes',
             'StormClimatology', 'WeatherStatistics'],
 'weather': ['SynopticStorms', 'DailyWeather']}


def kind(name):
    return KINDS.get(name, "number")


def structural(name):
    return name in GEOMETRY or KINDS.get(name) == "index"
